install:
	@echo "Устанавливаем зависимости"
	npm install


build:
	@echo "Собираем бекенд"
	npm run build

run:
	@echo "Запуск проекта"
	npm run start

install-run:
	@echo "Устанавливаем зависимости и запускаем бекенд"
	npm install
	npm run start
