name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -r ./path/to/your/app ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/deploy/directory

    - name: Execute remote commands
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /path/to/deploy/directory
        docker-compose down
        docker-compose pull
        docker-compose up -d
        EOF
