# цели по умолчанию и их действия
.DEFAULT_GOAL := init

# цели и их действия
init:
	npm i

build:
	npm run build

migrate:
	npm run migrate

run:
	npm start

# определение целей как фиктивных
.PHONY: init build migrate run
