.PHONY: serve build

# Цель для установки зависимостей
install:
    npm install

# Цель для сборки приложения
build:
    npm run build

# Цель для запуска приложения
start:
    npm start

# Цель для проверки кода на наличие ошибок и стилистических проблем
lint:
    npm run lint

# Цель для запуска тестов
test:
    npm test

# Цель для очистки собранных файлов
clean:
    rm -rf dist

# Цель по умолчанию
.DEFAULT_GOAL := start